### ISSUE TITLE
playersはhashsetで良かったのでは

### ISSUE THREAD

**Issue by kanais7** [k-hamada/HAL#31]

**Comment by kanais7** [comment]
自分で書いておいて情報無さすぎて良くわからなかったです！:bow::bow::bow:
Closeしたい

**Comment by k-hamada** [comment]
server での `GameModel.players`？
取得がちょっと面倒になるのと、`Player` に等値かの実装が必要なのと、 *`Hashset` の説明をしなければいけないのが大変そう* 。
